dset_dir: "/kaggle/working/dataset"
train_size: 50000
test_size: 5000
log: "logs"
logging_step: 100
validation_interval: 2000 # Save and valid have same interval
checkpoints: "/kaggle/working/weights"

batch_size: 16
lr: 0.001
RESNET_PLUS_PLUS: False
IMAGE_SIZE: 1500
CROP_SIZE: 224