segment_dset_dir: "/kaggle/working/dataset"
cd_dset_dir: "/kaggle/input/s2looking/S2Looking/S2Looking"
segment_train_size: 50000
segment_test_size: 5000
cd_train_size: 50000
cd_test_size: 5000
log: "logs"
logging_step: 100
validation_interval: 3000 # Save and valid have same interval
checkpoints: "/kaggle/working/weights"
batch_size: 16
lr: 0.001
IMAGE_SIZE: 1500
CROP_SIZE: 224