dset1_dir: "/root/alabama/alabama"
dset2_dir: "/root/resunet/data"
log: "logs"
logging_step: 100
validation_interval: 5 # Save and valid have same interval
checkpoints: "weights"
batch_size: 8
lr: 0.001
IMAGE_SIZE: 1500
CROP_SIZE: 224