dset1_dir: "/root/alabama/alabama"
cd_dset_dir: "/root/resunet/data/"
log: "logs"
logging_step: 50
validation_interval: 1750 # Save and valid have same interval
checkpoints: "weights"
batch_size: 8
lr: 0.001
IMAGE_SIZE: 1500
CROP_SIZE: 224