segment_dset_dir: "/root/alabama/alabama"
cd_dset_dir: "/root/alabama/alabama"
log: "logs"
logging_step: 100
validation_interval: 3000 # Save and valid have same interval
checkpoints: "segment_weights"
batch_size: 8
lr: 0.003
IMAGE_SIZE: 1500
CROP_SIZE: 224