dset1_dir: "/root/alabama/alabama"
dset2_dir: "/root/xbd"
log: "logs"
logging_step: 50
validation_interval: 3500 # Save and valid have same interval
checkpoints: "weights"
batch_size: 8
lr: 0.001
IMAGE_SIZE: 1500
CROP_SIZE: 224