segment_dset_dir: "/content/dataset/aicrowd"
cd_dset_dir: "/root/resunet/data/"
segment_train_size: 50000
segment_test_size: 5000
cd_train_size: 50000
cd_test_size: 5000
log: "logs"
logging_step: 100
validation_interval: 2000 # Save and valid have same interval
checkpoints: "/content/weights"
batch_size: 16
lr: 0.001
IMAGE_SIZE: 1500
CROP_SIZE: 224